name: Generate Devvit Fixtures and DB

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Full history is required to be able to push a commit back.
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # Use the version declared in .nvmrc if present; otherwise default to 20.x
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate chunks
        run: npm run scripts:generate-chunks

      - name: Generate SQLite DB
        run: npm run scripts:generate-sqlite-db

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_PAT }}
          commit-message: 'chore: update devvit-docs.db and fixtures'
          title: 'chore: update devvit-docs.db and fixtures'
          body: 'This PR was created automatically.'
          branch: auto/update-docs
          add-paths: |
            db/devvit-docs.db
            fixtures/**

      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-url != ''
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT }}
        run: |
          gh pr merge --auto --squash "${{ steps.cpr.outputs.pull-request-url }}"
